version: '3'

services:
  php-fpm:
    build:
      context: ./duca/docker/php-fpm
    volumes:
      - .:/var/www/html
    user: 1000:1000

  node:
    build:
      context: ./duca/docker/node
    volumes:
      - .:/var/www
    user: 1000:1000
    ports:
      - "35729:35729"

  nginx:
    build:
      context: ./duca/docker/nginx
    volumes:
      - .:/var/www/html
      - ./duca/docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./duca/docker/nginx/sites/:/etc/nginx/sites-available
      - ./duca/docker/nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
      - node
    ports:
      - "80:80"
      - "443:443"
